### ISSUE TITLE
编译不过去！ComplieInFile是什么

### ISSUE THREAD

**Issue by wang2650** [night-moon-studio/DynamicPlugIn#1]
ComplieInFile 参数报错。 这个是哪来的？源码都搜不到这个参数。

**Comment by NMSAzulX** [comment]
请获取最新版

已修复：
https://github.com/night-moon-studio/DynamicPlugin/blob/master/src/DynamicPlugIn/ReWriter.cs#L54

**Comment by NMSAzulX** [comment]
ComplieInFile 是将内容编译到 DLL 中， 新版 Natasha 使用枚举来表示。
